[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "pyosh"
authors = [{name = "Klaus G. Paul", email = "20340525+KlausGPaul@users.noreply.github.com"}]
dynamic = ["version", "description"]
